apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 20i1815/e1-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi" # Minimum memory required
              cpu: "250m"     # Minimum CPU required
            limits:
              memory: "512Mi" # Maximum memory the container can use
              cpu: "500m"     # Maximum CPU the container can use
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer # Exposes the service publicly
