apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shersher/scd-assignment-3:ep5frontend-image
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
      nodeSelector:
        nodeType: frontend
