apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 20i1815/e1-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017" # MongoDB service URL
          resources:
            requests:
              memory: "128Mi" # Minimum memory required
              cpu: "250m"     # Minimum CPU required
            limits:
              memory: "512Mi" # Maximum memory the container can use
              cpu: "500m"     # Maximum CPU the container can use
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
